import 'package:rmenu/model/menuitem.dart';

List<String> g_listCategory = ["Appetizers", "Entrees", "Sandwiches", "Cold", "Hot", "Soup & Salad Combos", "Fajitas", "Tacos"];
List<MenuItem> g_listMenuItem = [
  MenuItem(1, "Iceberg Wedge Salad with House Cured Bacon",
      "tomato salsa gorgonzola", 7.5),
  MenuItem(1, "Sautéed Shredded Brussels Sprouts", "bacon hazelnuts gorgonzola",
      6.95),
  MenuItem(2, "Farfalle Pasta with Braised Pork in Tomato Cream", "capers butternut squash kale",
      12.95),
  MenuItem(2, "Stout Braised Bratwusrt", "horseradish mashed potatoes roasted root veggies grilled onion ",
      13.95),
  MenuItem(2, "Salmon & Crispy Tofu in Yellow Curry Sauce", "vegetable sauté golden raisin chutney",
      15.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(2, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(3, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(5, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(5, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(6, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95),
  MenuItem(9, "Sesame Shrimp", "udon noodles ramen broth shiitake mushrooms bean sprouts scallions",
      13.95)
];
